### ISSUE TITLE
Unstable simulations are not caught by buildkite, LES_driven_SCM actually breaking

### ISSUE THREAD

**Issue by ilopezgp** [CliMA/TurbulenceConvection.jl#574]
I just realized that the MSE buildkite tests can pass without the simulation reaching the end time. This situation is frequently seen in the LES_driven_SCM test. Examples in closed PRs,

- In PR #567 , the simulation errored 97% into the simulation. The MSE comparison is at time t=21390s. 
- In PR #564 , the simulation errored 89% into the simulation. The MSE comparison is at time t=19710s.

I attach an example of this behavior from the buildkite of PR #564. This issue has two components,

- The current integration tests are fault tolerant, they shouldn't be.
- The default LES_driven_SCM case breaks.

<img width="1127" alt="Screen Shot 2021-11-17 at 11 49 06 PM" src="https://user-images.githubusercontent.com/38085953/142373842-754f54da-3165-43c3-9854-9864de08bdd1.png">

**Comment by jakebolewski** [comment]
I think for this you probably want some sort of state dump at upon aborting (ex. simulation time, number of steps, run parameters).  Then the CI can see if this abort state dump file exists for a particular run and raises an proper error exit code at the end.  This will help with calibration as well because the error will have some context with it's state so you don't have to do the extra work of trying to figure out which parameters caused the abort to happen.

**Comment by charleskawczynski** [comment]
Hmm, #575 adds a test on the ode integrator that we've reach `t_max`, and adds post-run tests (which ensure NaN is not in the solution). But maybe we just need the NaNs check? Alternatively we could return the a success flag and throw the error after the state dump / comparison / mse computations. Yeah, that's probably more helpful. Will open a PR.
